config/routes.rb
Fortunka::Application.routes.draw do
  resources :fortunes

root :to => 'fortunes#index'
  end

app/models/fortune.rb
class Fortune < ActiveRecord::Base
    cattr_reader :per_page
    @@per_page = 5
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fortunes_controller.rb
class FortunesController < ApplicationController
  # GET /fortunes
  # GET /fortunes.json
  def index
    @fortunes = Fortune.paginate :page => params[:page]

  # @fortunes = Fortune.all
  
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fortunes }
    end
  end

  # GET /fortunes/1
  # GET /fortunes/1.json
  def show
    @fortune = Fortune.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fortune }
    end
  end

  # GET /fortunes/new
  # GET /fortunes/new.json
  def new
    @fortune = Fortune.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fortune }
    end
  end

  # GET /fortunes/1/edit
  def edit
    @fortune = Fortune.find(params[:id])
  end

  # POST /fortunes
  # POST /fortunes.json
  def create
    @fortune = Fortune.new(params[:fortune])

    respond_to do |format|
      if @fortune.save
        format.html { redirect_to @fortune, notice: 'Fortunka utworzona.' }
        format.json { render json: @fortune, status: :created, location: @fortune }
      else
        format.html { render action: "new" }
        format.json { render json: @fortune.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fortunes/1
  # PUT /fortunes/1.json
  def update
    @fortune = Fortune.find(params[:id])

    respond_to do |format|
      if @fortune.update_attributes(params[:fortune])
        format.html { redirect_to @fortune, notice: 'Fortunka wyedytowana.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fortune.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fortunes/1
  # DELETE /fortunes/1.json
  def destroy
    @fortune = Fortune.find(params[:id])
    @fortune.destroy

    respond_to do |format|
      format.html { redirect_to fortunes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fortunes_helper.rb
module FortunesHelper
end

app/views/fortunes/_form.html.erb
<%= simple_form_for(@fortune) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :quotation %>
    <%= f.input :source %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/fortunes/edit.html.erb
<table class="btn-danger"><tr><td>
<h1>Edycja cytatu</h1>

<%= render 'form' %>

<div class="btn"><%= link_to 'Pokaż', @fortune %></div>
<div class="btn"><%= link_to 'Powrót', fortunes_path %></div>
</td></tr></table>

app/views/fortunes/index.html.erb
<h1>Lista cytatów</h1>

<table class="btn2">
  <tr>
    <td colspan="2"><div class="btn"><%= will_paginate @posts %></div></td>
  </tr>

<% @fortunes.each do |fortune| %>
  <tr>
    <td colspan="2"><p class="btn-info"><%= fortune.quotation %></p></td>
  </tr>
  <tr>
     <td align="left"><em>autor: <%= fortune.source %></em></td>
     <td align="right">
        <div class="btn"><%= link_to 'Pokaż', fortune %></div>
        <div class="btn"><%= link_to 'Edytuj', edit_fortune_path(fortune) %></div>
        <div class="btn"><%= link_to 'Usuń', fortune, confirm: 'Napewno usunąć?', method: :delete %></div>
     </td>
  </tr>
<% end %>
</table>

<br />
<div class="btn"><%= will_paginate @posts %></div>
<div class="btn"><%= link_to 'Nowy cytat', new_fortune_path %></div>

app/views/fortunes/new.html.erb
<%# encoding: utf-8 %>
<table class="btn-danger"><tr><td>
<h1>Nowy cytat</h1>

<%= render 'form' %>

<div class="btn"><%= link_to 'Powrót', fortunes_path %></div>
</td></tr></table>

app/views/fortunes/show.html.erb
<table class="btn-inverse"><tr><td>
<p id="notice"><%= notice %></p>

<p>
  <b>Cytat:</b>
  <%= @fortune.quotation %>
</p>

<p>
  <b>Autor:</b>
  <%= @fortune.source %>
</p>


<div class="btn"><%= link_to 'Edycja', edit_fortune_path(@fortune) %></div>
<div class="btn"><%= link_to 'Powrót', fortunes_path %></div>
</td></tr></table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fortunka</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>